name: Check JaCoCo Coverage

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Oracle JDK 23
        run: |
          # Descarga el Oracle JDK 23 para la arquitectura de GitHub Actions
          wget https://download.oracle.com/java/23/latest/jdk-23_linux-x64_bin.tar.gz
          # Extrae el archivo descargado
          sudo tar -xvzf jdk-23_linux-x64_bin.tar.gz -C /opt/
          # Configura Java y Javac usando update-alternatives para usar Oracle JDK 23
          sudo update-alternatives --install /usr/bin/java java /opt/jdk-23/bin/java 1
          sudo update-alternatives --install /usr/bin/javac javac /opt/jdk-23/bin/javac 1
          # Verifica la versión instalada
          java -version

      - name: Build and test with Maven
        run: mvn clean verify

      - name: Fail PR if coverage is not 100%
        run: |
          if ! grep -q 'Rule violated for bundle' target/site/jacoco/jacoco.xml; then
            echo "All tests passed and coverage is 100%!"
          else
            echo "Coverage is below 100%!" >&2
            exit 1
