name: Check JaCoCo Coverage

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azul Zulu JDK 11.0.24
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.24'  # Especifica la versión exacta
          distribution: 'zulu'      # Distribución de Azul Zulu JDK

      - name: Build and test with Maven
        run: mvn clean verify

      - name: Fail PR if coverage is not 100%
        run: |
          if ! grep -q 'Rule violated for bundle' target/site/jacoco/jacoco.xml; then
            echo "All tests passed and coverage is 100%!"
          else
            echo "Coverage is below 100%!" >&2
            exit 1
          fi  # Asegúrate de cerrar el bloque if aquí
