name: Check JaCoCo Coverage

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azul Zulu JDK 11.0.24
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.24'  # Especifica la versión exacta
          distribution: 'zulu'      # Distribución de Azul Zulu JDK

      - name: Build and test with Maven
        run: mvn clean verify
